### PR TITLE
ReST API: add extra attributes to harvest authorisations and targets

### PR DESCRIPTION
**Pull request by hannakoppelaar**
This PR adds extra attributes to the /harvest-authorisations and /targets endpoints, in order to reduce the number of requests needed to render the corresponding pages in the UI.

### CODE REVIEW

**Review by jeremy-liss — APPROVED** [review]
Have tested it out and all working well. I've added changes to the UI to match the updated endpoints.

**Comment by leefrank9527** [comment]
Have had a test. The api returned the expected data. But on the UI, in the Seed section the Object string are shown in the "Harvest Auth" column instead of the name of the Harvest Auth. That would be nice if you could take a look. @jeremy-liss

**Comment by jeremy-liss** [comment]
@leefrank9527 there is another ticket to do that work once these endpoints are complete, so maybe better that I do that in another branch once this one is merged https://github.com/WebCuratorTool/webcurator/issues/152

**Comment by leefrank9527** [comment]
@jeremy-liss That does make sense to change the UI in another branch.  @hannakoppelaar @obrienben For this PR, it's good to me and can me merged.

**Pull request merged**
