### PR TITLE
Upgrade scripts v3

### PR DESCRIPTION
**Pull request by hannakoppelaar**
Added database upgrade scripts for all supported platforms. Note that the MySQL and Oracle scripts are the same, but I suggest we keep separate files for clarity. I haven't tested this on Oracle, although I've checked it against the Oracle documentation. 

I've also reorganised the db subproject. It's no longer a gradle project, since it now only contains sql files and shellscripts (there was some Spring demo code that I've removed).

And, while I was at it, I've applied some pending changes to the DDL from a pr in our old repo.

### CODE REVIEW

**Comment by obrienben** [comment]
@hannakoppelaar can you please test the commit I've added

**Comment by hannakoppelaar** [comment]
@obrienben I've added a fix for the null values in id_generator.

I did notice that ProfileImportForm.java, the class that had those Lombok annotations, is not being used. ProfileListController uses the ProfileImportCommand, which has a similar layout. Maybe we should delete ProfileImportForm.java?

**Comment by obrienben** [comment]
@hannakoppelaar ok I'll look at deleting it in another PR

**Comment by hannakoppelaar** [comment]
@obrienben another small addition: I found that the type of the column ig_value was too small. I've changed it to have the same type as the primary key columns.

**Comment by hannakoppelaar** [comment]
I've set a default for the HR_INDEX column, which is maintained by hibernate, but doesn't get a proper value in case of a certain (known but hard to fix) race condition. If this column is null, the queue page will not work properly.

**Comment by hannakoppelaar** [comment]
I just realised that the changes to the upgrade scripts that correspond to schema changes will also need to find their way into the install scripts. I'll fix that asap.

**Pull request merged**
