### PR TITLE
Master3.1 upgrade sftp rosetta api

### PR DESCRIPTION
**Pull request by leefrank9527**
Changed the submit-to-rosetta module to support sftp and rosetta api7.1

### CODE REVIEW

**Comment by obrienben** [comment]
@leefrank9527 what's the purpose behind removing those .arc test files? Was that intentional?

**Comment by leefrank9527** [comment]
@obrienben The .arc files are generated automaticly inside the temp directory when running the test cases. They are deleted accidently, but has no affect to any test cases. To make it consistent I added the arc files back.

**Comment by obrienben** [comment]
@leefrank9527 in testing today in UAT, unfortunately another error when archiving to Rosetta with this PR.
Could there be a missing dependency?

```
2022-03-07 16:27:26.262 +1300 ERROR [Thread-16] o.w.c.s.a.ArcDigitalAssetStoreService$ArchivingThread (ArcDigitalAssetStoreService.java:930) - Could not archive 1000363300
java.lang.NoClassDefFoundError: org/jaxen/NamespaceContext
        at org.dom4j.DocumentFactory.createXPath(DocumentFactory.java:230)
        at org.dom4j.tree.AbstractNode.createXPath(AbstractNode.java:207)
        at org.dom4j.tree.AbstractNode.selectSingleNode(AbstractNode.java:183)
        at com.exlibris.core.sdk.formatting.DublinCore.getXPathValue(DublinCore.java:666)
        at com.exlibris.core.sdk.formatting.DublinCore.getValue(DublinCore.java:478)
        at com.exlibris.core.sdk.formatting.DublinCore.getDctermsValue(DublinCore.java:376)
        at nz.govt.natlib.ndha.wctdpsdepositor.mets.DnxMapperImpl.addAdditionalDcTermsElement(DnxMapperImpl.java:361)
        at nz.govt.natlib.ndha.wctdpsdepositor.mets.DnxMapperImpl.addHTMLSerialHarvestSpecificDc(DnxMapperImpl.java:324)
        at nz.govt.natlib.ndha.wctdpsdepositor.mets.DnxMapperImpl.populateIeDc(DnxMapperImpl.java:121)
        at nz.govt.natlib.ndha.wctdpsdepositor.mets.DnxMapperImpl.generateDnxFrom(DnxMapperImpl.java:76)
        at nz.govt.natlib.ndha.wctdpsdepositor.DpsDepositFacadeImpl.deposit(DpsDepositFacadeImpl.java:131)
        at nz.govt.natlib.ndha.wctdpsdepositor.DpsDepositFacadeImpl.deposit(DpsDepositFacadeImpl.java:114)
        at nz.govt.natlib.ndha.wctdpsdepositor.DpsDepositProxy.deposit(DpsDepositProxy.java:46)
        at org.webcurator.core.archive.dps.DPSArchive.submitToArchive(DPSArchive.java:185)
        at org.webcurator.core.store.arc.ArcDigitalAssetStoreService$ArchivingThread.run(ArcDigitalAssetStoreService.java:926)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.jaxen.NamespaceContext
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 16 common frames omitted
```

**Comment by leefrank9527** [comment]
Hi Ben,

The missing class was included inside '
com.exlibris.dps:dps-sdk-fat-all:5.5.0' in the store component. But I can't
remember why I commented it.

I added 'com.exlibris.dps:dps-sdk-fat-all:5.5.0' now, and updated #55.

BR
Frank

**Pull request merged**
