### PR TITLE
Master 3.1 added the missing commits and removed the bandwidth related codes.

### PR DESCRIPTION
**Pull request by leefrank9527**
Added the missing commits and removed the bandwidth related codes.

### CODE REVIEW

**Comment by obrienben** [comment]
Thanks @hannakoppelaar.
@leefrank9527 perhaps if there's no strong reason to use Void, then we should switch back to String types to be on the safe side?

**Comment by leefrank9527** [comment]
@hannakoppelaar @obrienben  The Void.class is only used for the controllers which return a void value. The return value (void) will not be set to any variables in this case. So I think this is safe to use Void.class.

**Comment by hannakoppelaar** [comment]
@obrienben @leefrank9527 I do remember seeing runtime exceptions caused by the use of Void in RestTemplate, but I am unable to reproduce them, so I guess this has been fixed in Spring.

I think we can merge this.

**Comment by leefrank9527** [comment]
@hannakoppelaar Yes. I think we can merge it. If there are issues happen we can resolve them case by case.

**Pull request merged**
