### PR TITLE
V3.0/add context path

### PR DESCRIPTION
**Pull request by leefrank9527**
1. Changed the URL combination mechanism of all client classes and configurations from  H1/H3/Store/WebApp sides. To replace the separated configuration items of "scheme/host/port" to an URL, so the URL could be manually combined flexibly.
2. Refined the resource file transferring method to support huge files.

### CODE REVIEW

**Comment by obrienben** [comment]
Reviewed and tested locally and in our UAT env, with and without setting a context of '/wct' in Webapp. Everything worked as expected.

**Comment by hannakoppelaar** [comment]
I'm getting this exception at index time:

Exception in thread "Thread-5" java.lang.IllegalArgumentException: [null/harvest-coordinator/finalise-index/{harvest-result-oid}] is not a valid HTTP URL
	at org.springframework.web.util.UriComponentsBuilder.fromHttpUrl(UriComponentsBuilder.java:290)
	at org.webcurator.core.store.IndexerBase.finaliseIndex(IndexerBase.java:93)
	at org.webcurator.core.store.IndexerBase.markComplete(IndexerBase.java:80)
	at org.webcurator.core.store.IndexerBase.run(IndexerBase.java:64)
	at java.lang.Thread.run(Thread.java:748)

The base URL of one of the Indexers is null, so it's probably not being propagated from the config. I'm not overriding that value in my application-local.properties, so it should be okay. Are you seeing this as well?

**Comment by leefrank9527** [comment]
@hannakoppelaar There are some Index related classes aren't initialed correctly. I've fixed them and update to this branch: v3.0/add-context-path.

**Review by hannakoppelaar — APPROVED** [review]

**Comment by hannakoppelaar** [comment]
I did an end-to-end test including indexing and it looks good now.

**Comment by obrienben** [comment]
Thanks @hannakoppelaar @leefrank9527.
I'll merge into master now

**Pull request merged**
