### PR TITLE
V3.1.4/no surt in cdx

### PR DESCRIPTION
**Pull request by hannakoppelaar**
Fix for #87

### CODE REVIEW

**Comment by leefrank9527** [comment]
@hannakoppelaar For the new updated screenshot, it will get the timestamp of URL from WARCs directly and not rely on the CDX. Is it possible to cancel this PR?

**Comment by hannakoppelaar** [comment]
@leefrank9527 The PR is still needed, but I will undo the last commit.

**Comment by hannakoppelaar** [comment]
The CDX format is now configurable again. This PR is ready for further review and merging.

**Comment by leefrank9527** [comment]
Thank you @hannakoppelaar, I'll check the changes asap.

**Comment by leefrank9527** [comment]
Went through the changes and tested them. All can do work well. Agree to merge the PR.

**Pull request merged**
